### ISSUE TITLE
[Feature] Here's a map I made

### ISSUE THREAD

**Issue by webdevan** [dsfsi/covid19africa#116]
Hello, I just thought I'd share this project I did in me free time:
https://sacovidmap.netlify.com/

![Screenshot from 2020-04-13 01-17-15](https://user-images.githubusercontent.com/10104686/79082316-13f05180-7d25-11ea-99f4-f56beb3ede27.png)
![Screenshot from 2020-04-13 01-17-37](https://user-images.githubusercontent.com/10104686/79082317-15ba1500-7d25-11ea-88c7-9094c981a7bc.png)
![Screenshot from 2020-04-13 01-18-31](https://user-images.githubusercontent.com/10104686/79082318-181c6f00-7d25-11ea-84d6-472e70d40a27.png)

My code is open source so anyone who who's working on anything related may use as much of it as they want:
https://github.com/webdevan/covid-map

Disclaimer: I'm not a scientist, so use this at your own risk.

I'm using the cumulative cases CSVs in this repo and should update automatically when new data is merged (if the structure changes my map will break!). I might submit an issue to discuss how we can structure the data in a way that can scale (because it is likely to keep expanding and evolving so getting some standards and structure going would be helpful).

Anyway, just wanted to put this out there so that people can use it, and if there's any feedback let me know.

**Comment by vukosim** [comment]
Thank you @webdevan
