### ISSUE TITLE
[Feature] John Hopkins data.

### ISSUE THREAD

**Issue by loulouOz** [dsfsi/covid19africa#223]
Hi There,

Wondering why you don't use John Hopkins data and build onto it? They have done (are doing) a tremendous work to pull together a fairly solid data.

If you need inspiration on presenting the data, here is my try: virus-corona.herokuapp.com

Cheers,
Louis

**Comment by vukosim** [comment]
@loulouOz Thanks for the comment. Does John Hopkins keep individual case data? For the moment I have not seen them do this so if there is a place where they have individual case data (which is what we are attempting to do) then we can look into merging things.

**Comment by loulouOz** [comment]
Indeed, apologies, I saw the detail level you are collecting only after I posted my comment. I will close the comment. 
All the best,
Louis
