### ISSUE TITLE
[Data] Updating

### ISSUE THREAD

**Issue by Ofentswe1** [dsfsi/covid19africa#33]
This data looks like its out dated I dont see recent cases for south africa, I only see about 554 cases @vukosim or the data is available here, if it here which file is the correct one?

**Comment by vukosim** [comment]
@Ofentswe1 for South Africa we have paused until we can get a better strategy to deal with the reporting from NICD and DoH. They no longer provide individual data.

**Comment by Ofentswe1** [comment]
Cool, I thought we have it ready
