### ISSUE TITLE
[Feature] number of tests per day per country in the dataset

### ISSUE THREAD

**Issue by millzon** [dsfsi/covid19africa#49]
I was wondering if there is an idea of incorporating number of tests done per day per country in the current dataset. 

I am not sure how it could be integrated in the current line-list files but adding a column 'num_tests' could be an idea. 

alternatively a separate line-list with:  date, num_tests, positives could handle it.  

Thank you,
Million

**Comment by vukosim** [comment]
we could create a folder for test and statistics, would the work?

**Comment by millzon** [comment]
cool, that works!
