### ISSUE TITLE
[Data] Validation of line list data for a few countries

### ISSUE THREAD

**Issue by TshepisoMokoena** [dsfsi/covid19africa#94]
**Problem description**

We would like to do the following analysis per African country:

1. Visualise the daily and cumulative cases since the first reported case
2. Calculate the relative risk of infection with COVID-19 by age group 
3. Analyse the distribution of the infection by gender and age
4. Analyze the change in the status of those who were affected over time (ie, "recovered", "ICU", "treatment" etc)

## Current bottlenecks 

Most of the data collected are not complete. For example, in most countries, there is a large chunk of missing data it the gender and age fields of the individuals who have tested positive.

Also for most countries, the current state of the individuals is unknown. So when new deaths occur it is hard to identify which individual in passed away.

In most countries only the first few cases that are reported on in detail, however this makes it hard to track the progression of the diseases via age and gender down the down

## If taking this up

Please help with validating the data for the country you have chosen

**Comment by vukosim** [comment]
@TshepisoMokoena can we update this with 2 or 3 countries that should be validated and examples of what you want as output.

**Comment by lizelgreyling** [comment]
Have you found any way to link outcomes to specific cases? For most African countries, it is only the first few cases that are reported on in detail. I have been able to find data about Egypt's first two cases, but even their gender is not reported. Moreover, when deaths occur, it is impossible to link it to a specific case. Might it be useful to keep separate line lists for deaths? It seems like more information is reported for a deaths (gender, co-morbidity, etc), but this data can't be added to the original line list as the case number is not known.

**Comment by TshepisoMokoena** [comment]
> @TshepisoMokoena can we update this with 2 or 3 countries that should be validated and examples of what you wan

**Comment by TshepisoMokoena** [comment]
> Have you found any way to link outcomes to specific cases? For most African countries, it is only the first few cases that are reported on in detail. I have been able to find data about Egypt's first two cases, but even their gender is not reported. Moreover, when deaths occur, it is impossible to link it to a specific case. Might it be useful to keep separate line lists for deaths? It seems like more information is reported for a deaths (gender, co-morbidity, etc), but this data can't be added to the original line list as the case number is not known.

I haven't found a way around this. At the moment I will work on only the initial cases that are in detail and select a few countries to do the analysis
