### ISSUE TITLE
Time Series Africa Data (Death and Recovered)

### ISSUE THREAD

**Issue by hakymulla** [dsfsi/covid19africa#95]
The who_covid_19_sit_rep_time_series_africa.csv data which is the time Series Data for confirmed cases only exist. I think we should add the Deaths and Recovered Time Series data as well.

**Comment by esube** [comment]
I agree. We should add deaths, recovered, and even tests performed within 24 hours. Most countries report that data daily in aggregate. There is so many places we can look for these data.
Here's some:
For cases, deaths, recovered: [WHO daily brief](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/), [JHU](https://github.com/CSSEGISandData/COVID-19) cases data, [Worldometer](https://www.worldometers.info/coronavirus/)
For tests performed: [Worldometer](https://www.worldometers.info/coronavirus/)
See this on how they sourced African-only data from the JHU csvs: [BBC Coronavirus in Africa Tracker](https://www.bbc.co.uk/news/resources/idt-4a11d568-2716-41cf-a15e-7d15079548bc)

**Comment by hakymulla** [comment]
I just want to know what the naming convention should be, that of Confirmed cases is who_covid_19_sit_rep_time_series_africa.csv, what should that for deaths, recovered and test be?

**Comment by esube** [comment]
The are two ways to do this:
1) create new file for each of the things to track: cases, death, recovered, tests, etc. If you choose this option, I suggest to use a different naming convention that is more intuitive such as `africa_daily_time_series_cases.csv, africa_daily_time_series_deaths.csv, africa_daily_time_series_recovered.csv, africa_daily_time_series_tests.csv`

2) on the current existing file, add rows for each things to track. For example the current file has 44 rows (could expand to all 54 countries), you can add another 44 rows at the bottom for deaths, another 44 for recovered etc...

Note: the current file naming was to refer the source is the WHO situational daily report.

**Comment by vukosim** [comment]
@esube and @hakymulla are we done with this?

**Comment by esube** [comment]
Yes, this has been successfully started and being updated daily. Closing this issue.
